[default.extend-words]
ratatui = "ratatui"
crossterm = "crossterm"
rrmj = "rrmj"
librrmj = "librrmj"
kiriage = "kiriage"
ukeire = "ukeire"
kabe = "kabe"
renchan = "renchan"
honba = "honba"
tsumo = "tsumo"
furiten = "furiten"
dakaikan = "dakaikan"
chii = "chii"
pon = "pon"
kan = "kan"
ron = "ron"
yaku = "yaku"
bevy = "bevy"
serde = "serde"
proptest = "proptest"
